### ISSUE TITLE
Move custom runtimes and infra to eoapi-devseed

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/eoAPI#191]
let's move all eoapi Custom part to its own repo: https://github.com/developmentseed/eoapi-devseed 

/eoapi should just host the documentation and issues

**Comment by vincentsarago** [comment]
the runtimes are ✅ in https://github.com/developmentseed/eoapi-devseed

## TODO 

- [ ] remove infra and runtime code from this repo
- [ ] deploy a new stack with eoapi-devseed runtimes
- [ ] move the `*.eoapi.dev` URL to the new endpoints
- [ ] add data to the new database
